### ISSUE TITLE
List bank accounts for specific customer

### ISSUE THREAD

**Issue by stephangroen** [Sneek/gocardless-pro#1]
First: Thanks for this library, works like a charm.

On implementation I missed the function to list the CustomerBankAccounts for a specific Customer. I needed to check which accounts where added to a customer, rather without the need to list all accounts and loop through them to filter out the ones belonging to a single customer.

I've added the tests and function in the following PR.

**Comment by CristianGiordano** [comment]
Thanks, I'm glad you like the package. As is stated it's still very early on. I had a quick check of your pull request and can see the direction (similar to the listMandatesForCustomer method).

I have to admit, I wanted to make a simple class for the params but I think it's overkill. I've changed a bunch of the list methods and removed the listMandatesForCustomer method in favour of an array of options. Check out [this commit](https://github.com/Sneek/gocardless-pro/commit/5b977375ecbc0872c205744628b526f4785fcf3a).

It will allow you do to the following:

``` php
$accounts = $api->listCustomerBankAccounts(['customer' => $id]);
```

as well as allowing to pass through the limit clause etc.

On a side note, I've recently been added to the GoCardless private beta of their pro api client, it's really nice and provides an interface I was moving towards. They have things like:

``` php
$api->customers()->list($options)
```

It returns a paginator object, which can make the next request very easily. Again something else I was going to use.

Hopefully you won't have too many areas to fix with the latest change to the package.

p.s. Let me know your thoughts...

**Comment by stephangroen** [comment]
Thanks, you're change is indeed more of what I had in mind myself. But because you already implemented the same for mandates, I though I'd move forward on that. As your are saying, a class for the params might be overkill and different methods for all possible options will be overkill too. Certainly if others might require more and other options to be set on a request.

I'll be using your new commit to use the options array, won't be a problem.

It seems they have made quite some changes and improvements in the new private beta. We might be switching when it becomes stable. Until then, you're package helps us quite nice :)
