### ISSUE TITLE
Links are not ever copied to Entities

### ISSUE THREAD

**Issue by fyfey** [Sneek/gocardless-pro#10]
The ability to access the links e.g. the Bank account link on a Mandate from the Mandate object.

A simple array of links would suffice. The constructor for Mandate has the ability to add entities, but doesn't seem to be implemented as yet.

What are your thoughts on this?

**Comment by CristianGiordano** [comment]
Should be easy enough I think. We will need to remove them when updating etc if they are there. I'd need to refresh my knowledge on the API.

If we add the property 'links' it should be added as an array when returning from the API, add a couple of accessors etc.
