### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by fyfey** [Sneek/gocardless-pro#13]
Currently, the only way to set metadata is using ::fromArray

I'm creating models using `new Customer` and would like to build up the model using the chaining API.

Not every model has a metadata i.e. Creditor https://developer.gocardless.com/pro/2015-04-29/#api-endpoints-creditors

I suggest implementing a trait to handle handle this. This also has the benefit that the fromArray method will automatically work without having to instantiate the Meta object.

I've opened a pull request with my changes. I've implemented all of the same functionality that existed on the Meta class and have created tests.

**Comment by CristianGiordano** [comment]
Merged, thanks.
