### ISSUE TITLE
Mandate in Payment::toArray

### ISSUE THREAD

**Issue by fyfey** [Sneek/gocardless-pro#19]
mandate is only removed from the resulting array if `mandate` is an instance of `Mandate`

I believe this to be an error as it's not a true representation of the model.

Pull request submitted

**Comment by CristianGiordano** [comment]
Do you have a test / use case for this? When would it not be an instance of `Mandate`?

**Comment by fyfey** [comment]
If I were to retrieve the Payment from the API the mandate would never be set?

**Comment by CristianGiordano** [comment]
The mandate property would be null, if you call the `toArray` method this is what you can expect:

```
Array
(
    [charge_date] => 2015-05-28
    [amount] => 1000
    [currency] => GBP
    [status] => pending_submission
    [id] => PM0000FJVFR59Y
    [created_at] => 2015-05-20T15:47:25.047Z
    [links] => Array
        (
            [mandate] => MD00007JC7N8AE
            [creditor] => CR0000399HQ01C
        )

)
```

Does that help?

**Comment by fyfey** [comment]
Ah, sorry. I'm being stupid.

My code was throwing an exception that mandate doesn't exist on my model, but it was coming from the link and not the model array itself.

You can close this issue.

**Comment by CristianGiordano** [comment]
No worries, it's late in the day!
