### ISSUE TITLE
Support for Guzzle 6

### ISSUE THREAD

**Issue by stephangroen** [Sneek/gocardless-pro#29]
I've opened up a pull request with support for Guzzle 6. Guzzle 6 is now PSR-7 compatible, so (finally) the API will not change that much anymore. With this library on Guzzle 6, it's easier to use in combination with other libraries that also support/require Guzzle 6.

**Comment by CristianGiordano** [comment]
Thanks for the pull request. I've finally managed to pull finger out and get this done. 

cb9ce48c0bb64055c32fda68738b1898f12b53de
