### ISSUE TITLE
Extend the API to include ability to fetch Mandate PDFs

### ISSUE THREAD

**Issue by fyfey** [Sneek/gocardless-pro#7]
The 2 endpoints that deal with mandate PDFs are not yet implemented:
- GET mandate/$id (application/pdf)
- POST helpers/mandate

These return the DirectDebit mandate forms that can be filled in and sent off by the customer.

I've opened a pull request with these extra methods.

**Comment by CristianGiordano** [comment]
Merged 861c55a990183ba85fe5ca67b1bbf4981c2db934
