### ISSUE TITLE
Implement Updates to API

### ISSUE THREAD

**Issue by CristianGiordano** [Sneek/gocardless-pro#9]
GoCardless have updated their API, changes should be reflected in the package.

https://gocardless.com/blog/new-api-release/

**Comment by stephangroen** [comment]
I have an updated version ready, which uses the new authentication. But due to changes, this will break old versions. Do you want to keep supporting both auth methods?

See: https://github.com/stephangroen/gocardless-pro/commit/6c7bdcc1ed3d54987ca45091fafebe1c95b5cdcf

**Comment by stephangroen** [comment]
This project could use versioning, so people can pin a specific version in composer. We now pin this on specific commits.

**Comment by CristianGiordano** [comment]
Hi, yes I was thinking about doing exactly that. Tag this current version as 1.0.0 then merge your new auth branch as 1.1.0.

What do you think of that?

**Comment by stephangroen** [comment]
That would be great. People that haven't upgraded their own app to use the new API version yet can pin on 1.0.0 and after your app is ready you can use 1.1.0. This is also great for future updates.

**Comment by CristianGiordano** [comment]
All versioned and tagged, thanks for your help :+1:
